plugins {
    id 'java'
    id 'application'
}

group = 'org.stac'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("tools.jackson.core:jackson-core:3.0.3")
    implementation("tools.jackson.core:jackson-databind:3.0.3")
}

application {
    mainClass = 'org.stac.PadelScraper'
}

test {
    useJUnitPlatform()
}