name: Playtomic Scraper Bot

on:
  schedule:
    # Runs every 15 minutes (UTC)
    - cron: '*/60 * * * *'
  workflow_dispatch: # Allows you to run it manually from the "Actions" tab

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/actions@v5.0.0

      - name: Compile and Run Scraper
        env:
          # Pass secrets into environment variables
          EMAIL: ${{ secrets.PLAYTOMIC_EMAIL }}
          PASSWORD: ${{ secrets.PLAYTOMIC_PASSWORD }}
          PUB_TOPIC: ${{ secrets.PUB_TOPIC }}
        run: |
          ./gradlew run --quiet